services:
  crawler_django:
    container_name: crawler_django
    build: .
    command: ['python', '/app/crawler/manage.py', 'runserver', '0:80']
    volumes:
      - .:/app
    ports:
      - 8025:80
  
  crawler_redis:
    container_name: crawler_redis
    image: redis:7.0.4-alpine
  
  crawler_beat:
    container_name: crawler_beat
    build: .
    command: ['sh', '-c', 'cd /app/crawler && celery -A crawler beat -l info']
    volumes:
      - .:/app
  
  crawler_worker:
    container_name: crawler_worker
    build: .
    command: ['sh', '-c', 'cd /app/crawler && celery -A crawler worker -l info']
    volumes:
      - .:/app
  
  crawler_firefox:
    container_name: crawler_firefox
    image: selenium/standalone-firefox
    ports:
      - 7900:7900
